// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package blockpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Index                int64          `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 string         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	PreviousHash         string         `protobuf:"bytes,3,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	Timestamp            int64          `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transaction          []*Transaction `protobuf:"bytes,5,rep,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetTransaction() []*Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type Transaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "blockpb.Block")
	proto.RegisterType((*Transaction)(nil), "blockpb.Transaction")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x49, 0x7b, 0xeb, 0xa5, 0x27, 0xe2, 0x70, 0xb8, 0x43, 0x06, 0x87, 0xd2, 0xa9, 0x53,
	0x07, 0x05, 0x1f, 0xc0, 0x49, 0x70, 0x0b, 0xbe, 0x40, 0x1a, 0x2b, 0x0d, 0xda, 0x9c, 0x90, 0x9c,
	0x8a, 0xef, 0xe4, 0x4b, 0x4a, 0x63, 0xa5, 0x75, 0xfb, 0xff, 0xff, 0x0b, 0xe1, 0xe3, 0x80, 0x1c,
	0x3e, 0xc8, 0xbe, 0xf7, 0x21, 0x12, 0x13, 0x9e, 0x73, 0x09, 0x43, 0xfb, 0x2d, 0xa0, 0x7a, 0x5c,
	0x33, 0x5e, 0xa0, 0x72, 0xfe, 0x75, 0xfc, 0x52, 0xa2, 0x11, 0x5d, 0xa9, 0x7f, 0x0b, 0x22, 0x9c,
	0x26, 0x93, 0x26, 0x55, 0x34, 0xa2, 0xab, 0x75, 0xce, 0xd8, 0xc2, 0x75, 0x88, 0xe3, 0xa7, 0xa3,
	0x25, 0x3d, 0xad, 0xac, 0xcc, 0xec, 0xdf, 0x86, 0xb7, 0x50, 0xb3, 0x9b, 0xc7, 0xc4, 0x66, 0x0e,
	0xea, 0x94, 0x7f, 0xdc, 0x07, 0x7c, 0x00, 0xc9, 0xd1, 0xf8, 0x64, 0x2c, 0x3b, 0xf2, 0xaa, 0x6a,
	0xca, 0x4e, 0xde, 0x5d, 0xfa, 0x4d, 0xaa, 0x7f, 0xd9, 0x99, 0x3e, 0x3e, 0x6c, 0x9f, 0x41, 0x1e,
	0xd8, 0x2a, 0xf7, 0x16, 0x69, 0xce, 0xc6, 0xb5, 0xce, 0x19, 0x6f, 0xa0, 0x60, 0xda, 0x74, 0x0b,
	0x26, 0x54, 0x70, 0x36, 0xd6, 0xd2, 0xe2, 0x79, 0xf3, 0xfc, 0xab, 0xc3, 0x55, 0x3e, 0xc5, 0xfd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x35, 0x38, 0x56, 0x19, 0x01, 0x00, 0x00,
}
