// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package blockpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transaction          []*Transaction `protobuf:"bytes,2,rep,name=transaction,proto3" json:"transaction,omitempty"`
	Hash                 string         `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransaction() []*Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BlockHeader struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PreviousHash         string   `protobuf:"bytes,2,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	CloudAddress         string   `protobuf:"bytes,4,opt,name=cloudAddress,proto3" json:"cloudAddress,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MerkleRoot           string   `protobuf:"bytes,6,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	Version              float32  `protobuf:"fixed32,7,opt,name=version,proto3" json:"version,omitempty"`
	Size                 int64    `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockHeader) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *BlockHeader) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *BlockHeader) GetCloudAddress() string {
	if m != nil {
		return m.CloudAddress
	}
	return ""
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

func (m *BlockHeader) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TxType               int32    `protobuf:"varint,2,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	Doc                  string   `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	AgentOrganization    string   `protobuf:"bytes,6,opt,name=agentOrganization,proto3" json:"agentOrganization,omitempty"`
	Nonce                uint64   `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId              uint32   `protobuf:"varint,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              []byte   `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	InputData            string   `protobuf:"bytes,11,opt,name=inputData,proto3" json:"inputData,omitempty"`
	RecordId             string   `protobuf:"bytes,12,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	UserSign             []byte   `protobuf:"bytes,22,opt,name=userSign,proto3" json:"userSign,omitempty"`
	DocSign              []byte   `protobuf:"bytes,23,opt,name=docSign,proto3" json:"docSign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTxType() int32 {
	if m != nil {
		return m.TxType
	}
	return 0
}

func (m *Transaction) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *Transaction) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetAgentOrganization() string {
	if m != nil {
		return m.AgentOrganization
	}
	return ""
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetInputData() string {
	if m != nil {
		return m.InputData
	}
	return ""
}

func (m *Transaction) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *Transaction) GetUserSign() []byte {
	if m != nil {
		return m.UserSign
	}
	return nil
}

func (m *Transaction) GetDocSign() []byte {
	if m != nil {
		return m.DocSign
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "blockpb.Block")
	proto.RegisterType((*BlockHeader)(nil), "blockpb.BlockHeader")
	proto.RegisterType((*Transaction)(nil), "blockpb.Transaction")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xd2, 0x36, 0x69, 0x26, 0x05, 0x81, 0xb5, 0xda, 0x35, 0x1f, 0x42, 0x55, 0x4f, 0x3d,
	0xac, 0x7a, 0x00, 0x89, 0x3b, 0x88, 0xc3, 0xee, 0x09, 0xc9, 0xec, 0x7d, 0xe5, 0xc6, 0xa3, 0xd6,
	0xda, 0xd4, 0x8e, 0x6c, 0xa7, 0x6a, 0xf7, 0xc6, 0x2f, 0xe6, 0xce, 0x09, 0x79, 0x92, 0xd2, 0x14,
	0x6e, 0xf3, 0xe6, 0xcd, 0xbc, 0xc9, 0x7b, 0x56, 0xa0, 0x5c, 0xd7, 0xb6, 0x7a, 0x5a, 0x35, 0xce,
	0x06, 0xcb, 0x72, 0x02, 0xcd, 0x7a, 0xf1, 0x33, 0x81, 0xc9, 0xd7, 0x58, 0xb3, 0x5b, 0xc8, 0xb6,
	0x28, 0x15, 0x3a, 0x9e, 0xcc, 0x93, 0x65, 0xf9, 0xf1, 0x6a, 0xd5, 0xcf, 0xac, 0x88, 0xbf, 0x23,
	0x4e, 0xf4, 0x33, 0xec, 0x33, 0x94, 0xc1, 0x49, 0xe3, 0x65, 0x15, 0xb4, 0x35, 0x3c, 0x9d, 0x8f,
	0x2e, 0x56, 0x1e, 0xce, 0x9c, 0x18, 0x0e, 0x32, 0x06, 0xe3, 0xad, 0xf4, 0x5b, 0x3e, 0x9a, 0x27,
	0xcb, 0x42, 0x50, 0xbd, 0xf8, 0x95, 0x40, 0x39, 0xb8, 0xc1, 0xae, 0x60, 0xa2, 0x8d, 0xc2, 0x03,
	0x7d, 0xc8, 0x48, 0x74, 0x80, 0x2d, 0x60, 0xd6, 0x38, 0xdc, 0x6b, 0xdb, 0xfa, 0xbb, 0xa8, 0x90,
	0x92, 0xc2, 0x45, 0x8f, 0x5d, 0x43, 0xa6, 0xf4, 0x06, 0x7d, 0x20, 0xfd, 0x99, 0xe8, 0x51, 0xdc,
	0xad, 0x6a, 0xdb, 0xaa, 0x2f, 0x4a, 0x39, 0xf4, 0x9e, 0x8f, 0xbb, 0xdd, 0x61, 0x8f, 0xbd, 0x87,
	0x22, 0xe8, 0x1d, 0xfa, 0x20, 0x77, 0x0d, 0x9f, 0xd0, 0xe5, 0x73, 0x83, 0x7d, 0x00, 0xd8, 0xa1,
	0x7b, 0xaa, 0x51, 0x58, 0x1b, 0x78, 0x46, 0xfb, 0x83, 0x0e, 0xe3, 0x90, 0xef, 0xd1, 0xf9, 0x98,
	0x45, 0x3e, 0x4f, 0x96, 0xa9, 0x38, 0xc1, 0xe8, 0xd8, 0xeb, 0x67, 0xe4, 0x53, 0x92, 0xa4, 0x7a,
	0xf1, 0x3b, 0x85, 0x72, 0x10, 0x11, 0x7b, 0x09, 0xa9, 0x56, 0x64, 0xb7, 0x10, 0xa9, 0x56, 0xec,
	0x06, 0xf2, 0x70, 0x78, 0x0c, 0xc7, 0x06, 0xc9, 0xe6, 0x44, 0x64, 0xe1, 0xf0, 0x70, 0x6c, 0x90,
	0xbd, 0x82, 0x91, 0xb2, 0x55, 0x9f, 0x5e, 0x2c, 0xa3, 0x7c, 0xeb, 0xd1, 0xf5, 0x96, 0xa8, 0x8e,
	0x01, 0xee, 0x65, 0xdd, 0x22, 0xd9, 0x28, 0x44, 0x07, 0xd8, 0x2d, 0xbc, 0x96, 0x1b, 0x34, 0xe1,
	0xbb, 0xdb, 0x48, 0xa3, 0x9f, 0x25, 0x3d, 0x5c, 0xe7, 0xe4, 0x7f, 0x22, 0x6a, 0x18, 0x6b, 0x2a,
	0x24, 0x3b, 0x63, 0xd1, 0x01, 0xf6, 0x06, 0xa6, 0xd5, 0x56, 0x6a, 0xf3, 0xa8, 0x15, 0x19, 0x7a,
	0x21, 0x72, 0xc2, 0xf7, 0xea, 0x32, 0xbf, 0xe2, 0xdf, 0xfc, 0x38, 0xe4, 0x8d, 0x3c, 0xd6, 0x56,
	0x2a, 0x0e, 0xf4, 0x34, 0x27, 0x18, 0xf7, 0xb4, 0x69, 0xda, 0xf0, 0x4d, 0x06, 0xc9, 0x4b, 0xfa,
	0x9c, 0x73, 0x83, 0xbd, 0x83, 0xc2, 0x61, 0x65, 0x9d, 0x8a, 0x17, 0x67, 0xc4, 0x4e, 0xbb, 0xc6,
	0xbd, 0x62, 0x6f, 0x61, 0x1a, 0xfd, 0xfe, 0xd0, 0x1b, 0xc3, 0xaf, 0x49, 0xf5, 0x2f, 0x8e, 0x07,
	0x95, 0xad, 0x88, 0xba, 0xe9, 0x0e, 0xf6, 0x70, 0x9d, 0xd1, 0x2f, 0xf0, 0xe9, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0xe7, 0x16, 0x75, 0x11, 0x03, 0x00, 0x00,
}
